export const MENU = [
  {
    id: 0,
    name: "Margherita Pizza",
    type: "pizza",
    price: "$10",
    description:
      "Fresh basil, olive oil, and Roma tomatos on our signature sauce.",
    image: "/images/margPizza.png",
    featured: false,
  },
  {
    id: 1,
    name: "Pepperoni Pizza",
    type: "pizza",
    price: "$11",
    description: "Pepperoni and mozzarella on our signature sauce.",
    image: "/images/pepPizza.png",
    featured: true,
  },
  {
    id: 2,
    name: "Meat Lovers Pizza",
    type: "pizza",
    price: "$14",
    description:
      "Pepperoni, savory sausage, beef, and Canadian bacon all topped with mozzarella.",
    image: "/images/meatLovers.jpg",
    featured: false,
  },
  {
    id: 3,
    name: "Barbeque Chicken",
    type: "pizza",
    price: "$15",
    description:
      "Smothered in smoky BBQ sauce, then topped with grilled chicken, hickory-smoked bacon, mozzarella, and fresh-cut onions.",
    image: "/images/barbChicken.jpg",
    featured: false,
  },
  {
    id: 4,
    name: "Vegetarian",
    type: "pizza",
    price: "$12",
    description:
      "Green bell peppers, onions, mushrooms, black olives, and tomatoes, all topped with mozzarella.",
    image: "/images/vegPizza.jpg",
    featured: false,
  },
  {
    id: 5,
    name: "Hawaiian",
    type: "pizza",
    price: "$14",
    description:
      "Pineapple, Canadian bacon, and three-cheese blend on our signature sauce.",
    image: "/images/hawaiianPizza.jpg",
    featured: false,
  },
  {
    id: 6,
    name: "Sourdough Loaf",
    type: "bread",
    price: "$6",
    description: "A loaf of our sourdough.",
    image: "/images/breadPatrickOne.jpg",
    featured: true,
  },
  {
    id: 7,
    name: "Breakfast Bagel",
    type: "bread",
    price: "$4",
    description: "Our same sourdough recipe, but in breakfast form.",
    image: "/images/bagel.jpg",
    featured: false,
  },
  {
    id: 8,
    name: "English Muffin",
    type: "bread",
    price: "$4",
    description: "Sourdough english muffin with your choice of jam or jelly.",
    image: "/images/breadPatrickThree.jpg",
    featured: false,
  },
  {
    id: 9,
    name: "Soft Drink",
    type: "beverage",
    price: "$2",
    description: "A can of Coke, Sprite, or Diet Coke",
    image: "/images/cokeCan.jpg",
    featured: true,
  },
  {
    id: 10,
    name: "Bottled Water",
    type: "beverage",
    price: "$1",
    description: "",
    image: "/images/water.jpg",
    featured: false,
  },
  {
    id: 11,
    name: "Draft Beer - 20oz",
    type: "beverage",
    price: "$6",
    description:
      "Colorado Lager, Vienna Folksbeir, IPA, or Nitro Milk Stout all from local breweries.",
    image: "/images/logo.png",
    featured: false,
  },
];
